dist: trusty
sudo: false
language: node_js
node_js:
- 8.7.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-\\d+$/"
env:
  global:
  - NPM_REGISTRY=https://atomist.jfrog.io/atomist/api/npm/npm-dev-local
  - secure: RI7ky0satYk14phJ0QhvmMOiG6oM4Ftz2lh5YGlC9RsSZ/jLdVdSraTDt0j6SM7yL2BG6gQ5g/ljyH/7Q/fyuwwJA9SNpreCN2glSIr1HJ9cmZzmzwyhzQN7gSNu1lpqh5KhyhguBJ4/YaNiB4d1WCaXt6jA4SU503/oZPzVhZLxag9wJvLnSs+9enHIos0yBPg3kgd2H85niGKuEd0/XKTqCKr6ZLPbB9MCDvOKk/lvMDyddME4YwSWjqowkP86f0VRP7NGWcrdy5y/sGORPNOUFAZ/UJ3TiiU/KHOM1fDF9cxE8nT3GAsSQw9du+dl3REVwzfiS8hMOjLDiWFMUjbfzi6YJdWh3tYlAEZUArhmXj3+r2rkKXa5kG9cAnQwu1HSnmph58MgtNij+9Kk/wnB/obGw5jjTNrc1g8GkDnI8qPUuVkvXVBX7VC2YBNAr7gz6RCgc/C2XGXxOAFTHoKLc29llQ8/l3ZRedc6GngiJU/cPrA+iE1/PE9atotjgMmidi2SH5tnG/qeqdIzY+Fc2c5MZKHOu+5PJa8YFyHGKj7mLYUvnufw+NCvcZq5JbEeLg005IlITT9o1mKEurlGaP5sm4/nD6gFG8XEu04AftDmCxJxZfr0T3NIXwN/6UmpFC/y8p93j1ujbED59oM5lkkGSIh7dlPs6Njyv+4=
  - secure: sTIpAYpOcK8b/e6frbFRA+/f6hO2QcQo2LkdqtsfUV423P8v681q/KW7fBNnzpwXxVNR4yajfRof1oH2NLwWOrNa1yy5Gmx3KXkK5EqBbhpqYySp64LstlN0nVYi2kcznnLCbUdYorvfQp+D/H3tnzNtvzuM6HLjKfl5V+h6HR17zItpIjO61+AF5Sb7IQb1KCbfvsH48m8W8Le4cu6oBAbjK3xoOpZfzM37evobrwV3VGJieFjjIgTgB6agb6u50/Y4EVyb7I8EVspPSzUoVSbPKzF8TBCPral9QCNizkFQdT1IzwdCr1Sd296K/YVv0BWlP8PKlSt/fqul3q+MAHCGzHbmv1G4PCsxNNfz+u/QgtuGowofE6848Sm+Y0yQOjIj5Layk4LZW/9b02dDLs8665HGelWaQcVj/MNogllcLWxvZfUR+G9tSjTL0vUCPXYqPIJapFe1cfubsvoM1bp+FWnZxUsrtcAm/ppZXqeZ44nbOXJnBNbQVyJhJ6FH/L6bqN/43+ahvVQxJ4nIPdfKJuyrdrCWbBGOMKWzTh8KJnpLpYKja4lBdy2mWxKYvZDsufcexfm5JXKLuxp+qTDBw8k+aXzU0oFZQrT5bvx2B3rrn2dV2LJBrqznXdUW0TqNY9bP6/wzOKwBqVXggthcIg19YudvcNn/OjUA82U=
  - secure: Q9HpOUvp4oPkMXody1f4WJLTlrrsx5TQhH19/3qxzrEgDWNytonDeCcl54qtgqkhbQl93PE0PXLPOUpNj1ZlCoB1Agnp29xYi1OKrNIxo1yYU22zI0hB263deYUZkrHWnQrnyVwjtbp+JVvrps8vzdDjo9+HFCNZqvpPcphCeqtW85vx8YA+ZY3eMuM7/tEL7Scgr+TJDHTYdIOiMKv6DBTkLNnp5DnoxZXbGolX44eCeAU3BBiSE/N/yGsqUWw1RBlqAgVGG1YWGwvFQ0ec+VM8wYXiPa2sE04WnA7N4HbUbsSDwqqVmv56Gp7fac0YsZAxKLWN8i3JBlW3TVv2+j6Qy+ony8S8GBTRWK+G+PZOTkyirGbV6eizbyZsV7Bdx6HRZumMdK11RFo0M18orlP0ytTc1i5WAHxzdj3h779fe87PUbBt8qEajGYQf42imTME7qHzszjsaCTcqZgRdQzW+1w+KcSr512G1we4pCP7FM2ZawaKYCJCSnUH2Xb3n7YvR6yuTJ17qsh9YNNc1YpTfY2ePd40z/s9+EkQJYsZLTnBkiIaQ+FMHr9CT9rzdKURGTOS4Yij1zBOKfo3hx8NVF+MScFkJQY+JRzo6HRVnGh7NMpCkgnhx7mhssWwc74nRIlgWjFgCtjwei8mxwW0KK6n41NhA6e/5NLjdOY=
before_install:
- "rm -f $HOME/.npm/_logs/*-debug.log"
- openssl aes-256-cbc -K $encrypted_536606bad75a_key -iv $encrypted_536606bad75a_iv
  -in scripts/.npmrc.enc -out $HOME/.npmrc -d
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.npm"
deploy:
- provider: cloudfoundry
  skip_cleanup: true
  api: https://api.run.pivotal.io
  username: "$CF_USER"
  password: "$CF_PASSWORD"
  organization: atomist
  app: ci-automation-staging
  space: development
  on:
    branch: master
- provider: cloudfoundry
  skip_cleanup: true
  api: https://api.run.pivotal.io
  username: "$CF_USER"
  password: "$CF_PASSWORD"
  organization: atomist
  space: production
  app: ci-automation
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build/typedoc
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
- provider: releases
  api_key: "$GITHUB_TOKEN"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
